---

version: "v-{build}"

image: Visual Studio 2015

clone_folder: C:\projects\clj-kondo

environment:
  GRAALVM_HOME: C:\projects\clj-kondo\graalvm\graalvm-ce-19.1.1

build_script:
- cmd: >-
    choco install windows-sdk-7.1

    call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd"

    powershell -Command "(New-Object Net.WebClient).DownloadFile('https://github.com/oracle/graal/releases/download/vm-19.1.1/graalvm-ce-windows-amd64-19.1.1.zip', 'graalvm.zip')"

    powershell -Command "Expand-Archive graalvm.zip graalvm"

    powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat', 'lein.bat')"

    call lein self-install

    call script/compile.bat

test: off

artifacts:
- path: clj-kondo-*-windows-amd64.zip
  name: clj-kondo
