name: clj-kondo
version: 2019.07.05-alpha
summary: A linter for Clojure code that sparks joy.
description: |
  A linter for Clojure code that sparks joy.
confinement: devmode
base: core18

parts:
  clj-kondo:
    plugin: dump
    source: https://github.com/borkdude/clj-kondo/releases/download/v$SNAPCRAFT_PROJECT_VERSION/clj-kondo-$SNAPCRAFT_PROJECT_VERSION-linux-amd64.zip

apps:
  clj-kondo:
    command: clj-kondo
